# Generated by Django 5.2.1 on 2025-05-25 09:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_userfollows_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(related_name='followers', through='authentication.UserFollows', through_fields=('user', 'followed_user'), to=settings.AUTH_USER_MODEL),
        ),
    ]
