# Generated by Django 5.2.1 on 2025-06-04 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfollows',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows_relations', to=settings.AUTH_USER_MODEL),
        ),
    ]
